# Generated by Django 6.0.4 on 2026-04-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='test-slug', unique=True),
            preserve_default=False,
        ),
    ]
