# Generated by Django 6.0.4 on 2026-04-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobiles'), ('laptop', 'Laptops'), ('clothing', 'Clothing'), ('watch', 'Watches'), ('shoes', 'Footwear'), ('jewellery', 'Jewellery'), ('books', 'Books')], default='mobile', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
